<?php
$ICEcoderUserSettings = array(
"versionNo"		=> "4.3",
"root"			=> "",
"checkUpdates"		=> true,
"openLastFiles"		=> true,
"findFilesExclude"	=> array(".doc",".gif",".jpg",".jpeg",".pdf",".png",".swf",".xml",".zip"),
"codeAssist"		=> true,
"visibleTabs"		=> false,
"lockedNav"		=> true,
"tagWrapperCommand"	=> "ctrl+alt",
"autoComplete"		=> "ctrl+space",
"password"		=> "",
"bannedFiles"		=> array(),
"bannedPaths"		=> array("/var/www/.git","/var/www/sites/all/modules","/var/www/sites/default/files"),
"allowedIPs"		=> array("*"),
"theme"			=> "default",
"fontSize"		=> "13px",
"lineWrapping"		=> true,
"indentWithTabs"	=> true,
"indentSize"		=> 4,
"pluginPanelAligned"	=> "left",
"bugFilePaths"		=> array(),
"bugFileCheckTimer"	=> 0,
"bugFileMaxLines"	=> 0,
"githubAuthToken"	=> "",
"plugins"		=> array(),
"githubLocalPaths"	=> array(),
"githubRemotePaths"	=> array(),
"previousFiles"		=> "",
"last10Files"		=> ""
);
?>